### PR TITLE
HTML/CSS enhancements

### PR DESCRIPTION
**Pull request by tomchadwin**

### CODE REVIEW

**Comment by NathanW2** [comment]
Are you able to run the command ok?

**Comment by tomchadwin** [comment]
Not tried, to be honest. From OSGeo4W shell?

**Comment by NathanW2** [comment]
Yes, although you will just need to do the pip installs first.

**Comment by tomchadwin** [comment]
Apologies: pip doesn't run for me from the OSGeo4W shell. Do I have to install Python manually, or set an env var to point to the OSGeo4W copy, or something?

Assess my ignorance by that question accordingly.

**Comment by NathanW2** [comment]
All good.  Let me remove the need to need those imports in the first
place.  No need to have them if using html output anyway.

**Comment by NathanW2** [comment]
You should be able to run a html report now with needing to install anything in pip

`python ogrcompare.py "test3.shp" test4.shp" --html > report.html`

**Comment by tomchadwin** [comment]
Think you might just have wiped my changes you just merged in?

**Comment by NathanW2** [comment]
Hmm really that's strange

**Comment by tomchadwin** [comment]
Yeah: 7c95f712afb9d2d8091954f51b71a93f875a2295 overwrote them.

**Comment by NathanW2** [comment]
Oops sorry about that. Not sure I messed that up

**Comment by tomchadwin** [comment]
Didn't do `git pull` before making your last changes?

**Comment by NathanW2** [comment]
Yeah or else I wouldn't have been able to push it up. Give me a sec and I
will fix it up

**Comment by tomchadwin** [comment]
No worries. I thought I'd done something wrong... Just looking forward to be able to run the command.

**Comment by NathanW2** [comment]
Should be good now.  Thanks for the find, sorry for my bad merge.

**Comment by tomchadwin** [comment]
Me with this repo today:


https://xkcd.com/1597/

**Comment by NathanW2** [comment]
:) yeah sorry about that. Should claim down a bit now

**Pull request merged**
